#!/usr/bin/env bash
# init-nightly-digest.sh — 初始化每日 nightly digest 骨架
# 用法: ./scripts/init-nightly-digest.sh [BRAIN_ROOT] [TARGET_DATE]

set -euo pipefail

BRAIN_ROOT="${1:-${BRAIN_PATH:-./vault-template}}"
TARGET_DATE="${2:-$(date -v-1d +%Y-%m-%d 2>/dev/null || date -d 'yesterday' +%Y-%m-%d)}"
CREATED_DATE="$(date +%Y-%m-%d)"
DIGEST_DIR="$BRAIN_ROOT/03-KNOWLEDGE/01-READING/04-DIGESTS"
REPORT_DIR="$BRAIN_ROOT/03-KNOWLEDGE/99-SYSTEM/03-INTEGRATION-REPORTS/run-reports/$TARGET_DATE"
DIGEST_FILE="$DIGEST_DIR/nightly-digest-$TARGET_DATE.md"

mkdir -p "$DIGEST_DIR" "$REPORT_DIR"

if [ ! -f "$DIGEST_FILE" ]; then
  cat > "$DIGEST_FILE" << DIGEST_EOF
---
title: "Nightly Digest ${TARGET_DATE}"
date: "${TARGET_DATE}"
created: "${CREATED_DATE}"
type: nightly-digest
status: draft
---

# 🌙 Nightly Digest — ${TARGET_DATE}

> AI 自动生成的每日知识摘要。从这里开始你的阅读。

---

## 02:00 Article Integration

<!-- 由 article-notes-integration pipeline 填写 -->
*Pending...*

---

## 03:00 Conversation Mining

<!-- 由 conversation-knowledge-mining pipeline 填写 -->
*Pending...*

---

## 04:00 Knowledge Amplification

<!-- 由 knowledge-flywheel-amplifier pipeline 填写 -->
*Pending...*

---

## 今日推荐阅读

<!-- 由 04:00 阶段综合判断后填写 -->

---

*Generated by Brain OS nightly pipeline*
DIGEST_EOF
  echo "✅ Created: $DIGEST_FILE"
else
  echo "ℹ️  Exists: $DIGEST_FILE"
fi

echo "report-dir: $REPORT_DIR"
