#!/usr/bin/env bash
# knowledge-lint.sh — Brain OS 知识库内容健康检查脚本
# 用法: ./scripts/knowledge-lint.sh [BRAIN_ROOT]
# 或者: source scripts/config.env && ./scripts/knowledge-lint.sh

set -euo pipefail

# ── 配置 ──────────────────────────────────────────────────────
# 优先用命令行参数，其次用环境变量，最后用默认值
BRAIN_ROOT="${1:-${BRAIN_PATH:-./vault-template}}"
DOMAINS_DIR="$BRAIN_ROOT/03-KNOWLEDGE/01-READING/01-DOMAINS"
REVIEWS_DIR="$BRAIN_ROOT/03-KNOWLEDGE/99-SYSTEM/lint-reports"
DATE=$(date +%Y-%m-%d)
REPORT="$REVIEWS_DIR/lint-$DATE.md"

mkdir -p "$REVIEWS_DIR"

# 计数器
RED=0
YELLOW=0
BLUE=0
RED_CONTENT=""
YELLOW_CONTENT=""
BLUE_CONTENT=""

echo "🔍 Knowledge Lint 开始扫描..."
echo "   Brain root: $BRAIN_ROOT"
echo "   扫描目录: $DOMAINS_DIR"
echo ""

# ── Check A: 必填字段 ──────────────────────────────────────────
echo "  [A] 检查 frontmatter 必填字段..."
A_ISSUES=""
REQUIRED_FIELDS=("title" "status" "date" "tags")

while IFS= read -r -d '' f; do
  FNAME=$(basename "$f" .md)
  for field in "${REQUIRED_FIELDS[@]}"; do
    if ! grep -q "^${field}:" "$f" 2>/dev/null; then
      A_ISSUES="$A_ISSUES\n- [[${FNAME}]] — 缺少 \`${field}\`"
      RED=$((RED + 1))
    fi
  done
  # 检查 source 相关字段
  if ! grep -qE "^(source|source_type|source_url):" "$f" 2>/dev/null; then
    A_ISSUES="$A_ISSUES\n- [[${FNAME}]] — 缺少 source 相关字段"
    RED=$((RED + 1))
  fi
done < <(find "$DOMAINS_DIR" -name "*.md" -not -name "*.template.md" -print0 2>/dev/null)

if [ -n "$A_ISSUES" ]; then
  RED_CONTENT="$RED_CONTENT\n### [Check A] 缺少必填字段\n$A_ISSUES\n"
fi

# ── Check B: 引号规范 ──────────────────────────────────────────
echo "  [B] 检查 frontmatter 引号规范..."
B_ISSUES=""

while IFS= read -r -d '' f; do
  FNAME=$(basename "$f" .md)
  TITLE_LINE=$(grep "^title:" "$f" 2>/dev/null | head -1 || true)
  if echo "$TITLE_LINE" | grep -qE '^title:[[:space:]]*[^"]' 2>/dev/null; then
    COLON_COUNT=$(echo "$TITLE_LINE" | grep -o ":" | wc -l | tr -d ' ')
    if [ "$COLON_COUNT" -gt 1 ]; then
      B_ISSUES="$B_ISSUES\n- [[${FNAME}]] — title 含多个冒号但未加引号"
      YELLOW=$((YELLOW + 1))
    fi
  fi
done < <(find "$DOMAINS_DIR" -name "*.md" -not -name "*.template.md" -print0 2>/dev/null)

if [ -n "$B_ISSUES" ]; then
  YELLOW_CONTENT="$YELLOW_CONTENT\n### [Check B] 引号规范问题\n$B_ISSUES\n"
fi

# ── Check C: Tag 统一性 ──────────────────────────────────────
echo "  [C] 检查 tag 统一性..."
C_ISSUES=""

ALL_TAGS=$(find "$DOMAINS_DIR" -name "*.md" -exec grep -h "^  - " {} \; 2>/dev/null | sed 's/^[[:space:]]*- //' | sort | uniq -c | sort -rn)
SINGLETON_TAGS=$(echo "$ALL_TAGS" | awk '$1 == 1 {print $2}' | head -10)
if [ -n "$SINGLETON_TAGS" ]; then
  C_ISSUES="$C_ISSUES\n**只出现1次的 tag（可能是孤立/拼写错误）**：\n"
  while IFS= read -r tag; do
    C_ISSUES="$C_ISSUES- \`$tag\`\n"
    BLUE=$((BLUE + 1))
  done <<< "$SINGLETON_TAGS"
fi

if [ -n "$C_ISSUES" ]; then
  BLUE_CONTENT="$BLUE_CONTENT\n### [Check C] Tag 统一性\n$C_ISSUES\n"
fi

# ── Check D: 过时声明 ──────────────────────────────────────────
echo "  [D] 检查过时声明（active 但超30天未更新）..."
D_ISSUES=""
CUTOFF_DATE=$(date -v-30d +%Y-%m-%d 2>/dev/null || date -d '30 days ago' +%Y-%m-%d 2>/dev/null || echo "1970-01-01")

while IFS= read -r -d '' f; do
  FNAME=$(basename "$f" .md)
  STATUS=$(grep "^status:" "$f" 2>/dev/null | head -1 | sed 's/^status:[[:space:]]*//' | tr -d '"' || true)
  UPDATED=$(grep "^updated:" "$f" 2>/dev/null | head -1 | sed 's/^updated:[[:space:]]*//' | tr -d '"' || true)
  CREATED=$(grep "^date:" "$f" 2>/dev/null | head -1 | sed 's/^date:[[:space:]]*//' | tr -d '"' || true)
  DATE_TO_CHECK="${UPDATED:-$CREATED}"
  if [[ "$STATUS" == "active" ]] && [[ -n "$DATE_TO_CHECK" ]] && [[ "$DATE_TO_CHECK" < "$CUTOFF_DATE" ]]; then
    D_ISSUES="$D_ISSUES\n- [[${FNAME}]] — status:active 但 ${DATE_TO_CHECK} 未更新"
    BLUE=$((BLUE + 1))
  fi
done < <(find "$DOMAINS_DIR" -name "*.md" -not -name "*.template.md" -print0 2>/dev/null)

if [ -n "$D_ISSUES" ]; then
  BLUE_CONTENT="$BLUE_CONTENT\n### [Check D] 过时声明候选（待复查）\n$D_ISSUES\n"
fi

# ── 生成报告 ──────────────────────────────────────────────────
TOTAL_FILES=$(find "$DOMAINS_DIR" -name "*.md" -not -name "*.template.md" 2>/dev/null | wc -l | tr -d ' ')

cat > "$REPORT" << REPORT_EOF
---
type: "lint-report"
date: "$DATE"
scanner: "knowledge-lint.sh"
---

# Knowledge Lint Report — $DATE

## 执行摘要

- **扫描文件数**：$TOTAL_FILES
- 🔴 高优先级问题：$RED 条
- 🟡 中优先级问题：$YELLOW 条
- 🔵 低优先级 / 建议：$BLUE 条

REPORT_EOF

if [ $RED -gt 0 ]; then
  printf "## 🔴 高优先级（需立即处理）\n" >> "$REPORT"
  printf "$RED_CONTENT\n" >> "$REPORT"
fi

if [ $YELLOW -gt 0 ]; then
  printf "## 🟡 中优先级（需跟进）\n" >> "$REPORT"
  printf "$YELLOW_CONTENT\n" >> "$REPORT"
fi

if [ $BLUE -gt 0 ]; then
  printf "## 🔵 低优先级 / 建议\n" >> "$REPORT"
  printf "$BLUE_CONTENT\n" >> "$REPORT"
fi

if [ $RED -eq 0 ] && [ $YELLOW -eq 0 ] && [ $BLUE -eq 0 ]; then
  printf "## ✅ 全部通过\n\n知识库内容健康，未发现问题。\n" >> "$REPORT"
fi

printf "\n---\n*Generated by knowledge-lint.sh at $(date)*\n" >> "$REPORT"

echo ""
echo "✅ Lint 完成："
echo "   🔴 $RED  🟡 $YELLOW  🔵 $BLUE"
echo "   报告：$REPORT"
